// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjVP-ut98Gz-MY-0Pr-zDR0XSvkWmDsJo',
    appId: '1:372579634671:web:e99aa087f758860f7dba1a',
    messagingSenderId: '372579634671',
    projectId: 'store-ac',
    authDomain: 'store-ac.firebaseapp.com',
    storageBucket: 'store-ac.firebasestorage.app',
    measurementId: 'G-4HE7CNCP76',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_dRrDnriYnbdLjiy6SLgUXWAqtTW4A8s',
    appId: '1:372579634671:android:0b7a6e70476c1a287dba1a',
    messagingSenderId: '372579634671',
    projectId: 'store-ac',
    storageBucket: 'store-ac.firebasestorage.app',
  );
}
